package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"
	"github.com/vigil/vigil/internal/output"
)

// ----------------------------------------------------------------------------
// Response types
// ----------------------------------------------------------------------------

type alert struct {
	ID             string                 `json:"id"`
	RuleID         string                 `json:"rule_id"`
	RuleName       string                 `json:"rule_name"`
	EventID        string                 `json:"event_id"`
	Severity       string                 `json:"severity"`
	Status         string                 `json:"status"`
	MatchedAt      string                 `json:"matched_at"`
	AcknowledgedAt string                 `json:"acknowledged_at,omitempty"`
	Note           string                 `json:"note,omitempty"`
	EventSnapshot  map[string]interface{} `json:"event_snapshot"`
}

type alertListResponse struct {
	Alerts []alert `json:"alerts"`
	Total  int     `json:"total"`
}

type alertAcknowledgeResponse struct {
	ID             string `json:"id"`
	Status         string `json:"status"`
	AcknowledgedAt string `json:"acknowledged_at"`
	Note           string `json:"note,omitempty"`
}

// ----------------------------------------------------------------------------
// Flag vars
// ----------------------------------------------------------------------------

var (
	alertsListStatus   string
	alertsListSeverity string
	alertsListRuleID   string
	alertsListFrom     string
	alertsListTo       string
	alertsListLimit    int

	alertsAcknowledgeNote string
)

// ----------------------------------------------------------------------------
// Parent command: vigil alerts
// ----------------------------------------------------------------------------

var alertsCmd = &cobra.Command{
	Use:   "alerts",
	Short: "View and manage security alerts",
	Long: `View and manage security alerts generated by detection rules.

Subcommands:
  list         List alerts (default: open)
  get          Get a single alert by ID
  acknowledge  Acknowledge an alert`,
}

// ----------------------------------------------------------------------------
// vigil alerts list
// ----------------------------------------------------------------------------

var alertsListCmd = &cobra.Command{
	Use:   "list",
	Short: "List alerts",
	RunE: func(cmd *cobra.Command, args []string) error {
		params := map[string]string{
			"limit":  fmt.Sprintf("%d", alertsListLimit),
			"status": alertsListStatus,
		}
		if alertsListSeverity != "" {
			params["severity"] = alertsListSeverity
		}
		if alertsListRuleID != "" {
			params["rule_id"] = alertsListRuleID
		}
		if alertsListFrom != "" {
			params["from_time"] = alertsListFrom
		}
		if alertsListTo != "" {
			params["to_time"] = alertsListTo
		}

		var resp alertListResponse
		if err := apiClient.Get("/v1/alerts", params, &resp); err != nil {
			output.PrintErrorFromErr(err)
			return nil
		}

		mode := output.ParseMode(globalOutput)
		if mode == output.ModeJSON {
			output.PrintJSON(resp)
			return nil
		}

		t := output.NewTable([]string{"ID", "Rule Name", "Severity", "Status", "Matched At"})
		for _, a := range resp.Alerts {
			id := a.ID
			if len(id) > 8 {
				id = id[:8]
			}
			t.Append([]string{id, a.RuleName, a.Severity, a.Status, a.MatchedAt})
		}
		t.Render()
		fmt.Printf("\nTotal: %d\n", resp.Total)
		return nil
	},
}

// ----------------------------------------------------------------------------
// vigil alerts get <id>
// ----------------------------------------------------------------------------

var alertsGetCmd = &cobra.Command{
	Use:   "get <id>",
	Short: "Get an alert by ID",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]

		var resp alert
		if err := apiClient.Get("/v1/alerts/"+id, nil, &resp); err != nil {
			output.PrintErrorFromErr(err)
			return nil
		}

		mode := output.ParseMode(globalOutput)
		if mode == output.ModeJSON {
			output.PrintJSON(resp)
			return nil
		}

		// Render event_snapshot as inline JSON, truncated to 200 chars.
		snapshotStr := ""
		if resp.EventSnapshot != nil {
			if b, err := json.Marshal(resp.EventSnapshot); err == nil {
				snapshotStr = string(b)
			}
		}
		if len(snapshotStr) > 200 {
			snapshotStr = snapshotStr[:200] + "..."
		}

		t := output.NewTable([]string{"Field", "Value"})
		t.Append([]string{"ID", resp.ID})
		t.Append([]string{"Rule ID", resp.RuleID})
		t.Append([]string{"Rule Name", resp.RuleName})
		t.Append([]string{"Event ID", resp.EventID})
		t.Append([]string{"Severity", resp.Severity})
		t.Append([]string{"Status", resp.Status})
		t.Append([]string{"Matched At", resp.MatchedAt})
		t.Append([]string{"Acknowledged At", resp.AcknowledgedAt})
		t.Append([]string{"Note", resp.Note})
		t.Append([]string{"Event Snapshot", snapshotStr})
		t.Render()
		fmt.Println()
		return nil
	},
}

// ----------------------------------------------------------------------------
// vigil alerts acknowledge <id>
// ----------------------------------------------------------------------------

var alertsAcknowledgeCmd = &cobra.Command{
	Use:   "acknowledge <id>",
	Short: "Acknowledge an alert",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		id := args[0]

		body := map[string]interface{}{"note": alertsAcknowledgeNote}
		var resp alertAcknowledgeResponse
		if err := apiClient.Post("/v1/alerts/"+id+"/acknowledge", body, &resp); err != nil {
			output.PrintErrorFromErr(err)
			return nil
		}

		mode := output.ParseMode(globalOutput)
		if mode == output.ModeJSON {
			output.PrintJSON(resp)
			return nil
		}

		t := output.NewTable([]string{"Field", "Value"})
		t.Append([]string{"Alert ID", resp.ID})
		t.Append([]string{"Status", resp.Status})
		t.Append([]string{"Acknowledged At", resp.AcknowledgedAt})
		if resp.Note != "" {
			t.Append([]string{"Note", resp.Note})
		}
		t.Render()
		fmt.Println()
		return nil
	},
}

// ----------------------------------------------------------------------------
// init: wire flags and subcommands
// ----------------------------------------------------------------------------

func init() {
	// alerts list
	alertsListCmd.Flags().StringVar(&alertsListStatus, "status", "open", "Filter by status: open|acknowledged|suppressed")
	alertsListCmd.Flags().StringVar(&alertsListSeverity, "severity", "", "Filter by severity: low|medium|high|critical")
	alertsListCmd.Flags().StringVar(&alertsListRuleID, "rule-id", "", "Filter by detection rule ID")
	alertsListCmd.Flags().StringVar(&alertsListFrom, "from", "", "Start time filter (RFC3339)")
	alertsListCmd.Flags().StringVar(&alertsListTo, "to", "", "End time filter (RFC3339)")
	alertsListCmd.Flags().IntVar(&alertsListLimit, "limit", 100, "Maximum number of alerts to return")

	// alerts acknowledge
	alertsAcknowledgeCmd.Flags().StringVar(&alertsAcknowledgeNote, "note", "", "Optional note to attach to the acknowledgement")

	// Register subcommands.
	alertsCmd.AddCommand(alertsListCmd)
	alertsCmd.AddCommand(alertsGetCmd)
	alertsCmd.AddCommand(alertsAcknowledgeCmd)
}
